name: Zad2 CI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Github source code checkout
      uses: actions/checkout@v4
    - name: 'Log to GitHub'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.ghToken}}
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.actor  }}/lekki-obraz
        flavour: latest=false
        tags: |
          type=semver,priority=200,pattern={{version}}
          type=sha,priority=100,prefix=sha-,format=short
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        file: ./Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: mode=max
        sbom: true
        cache-from: type=registry,ref=${{ github.actor }}/lekki-obraz-cache:cache
        cache-to: type=registry,ref=${{ github.actor }}/lekki-obraz-cache:cache,mode=max
    - name: Docker Scout
      id: docker-scout
      uses: docker/scout-action@v1
      with:
        command: cves
        image: ${{ steps.meta.outputs.tags }}
        only-severities: critical,high
        exit-code: true
    - name: Push Docker Image
      if: success()
      run: |
        docker buildx imagetools create --tag ghcr.io/${{github.actor}}/last-image:latest  ${{ steps.meta.outputs.tags }}
