name: Zad2 CI
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Github source code checkout
      uses: actions/checkout@v4
    - name: 'Log to GitHub'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: adrianw246
        password: ${{ secrets.ghToken }}
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/adrianw246/lekki-obraz
        flavour: latest=false
        labels:
          org.opencontainers.image.source: "https://github.com/adrianw246/zad2"
        tags: |
          type=semver,priority=200,pattern={{version}}
          type=sha,priority=100,prefix=sha-,format=short
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        file: ./Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: mode=max
        sbom: true
        cache-from: type=registry,ref=ghcr.io/adrianw246/lekki-obraz-cache:cache
        cache-to: type=registry,ref=ghcr.io/adrianw246/lekki-obraz-cache:cache,mode=max
    - name: log to DockerHub
      uses: docker/login-action@v3
      with:
        username: adrw246
        password: ${{ secrets.docker_token }}
    - name: Scan image for vulnerabilities with Trivy
      id: trivy-scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.meta.outputs.tags }}
        severity: HIGH,CRITICAL
        exit-code: 0
        format: table
        output: ./trivy-report.txt
    - name: Summary of vulnerabilities
      if: always()
      run: |
        echo "Trivy Scan Summary:" >> $GITHUB_STEP_SUMMARY
        if [ -f ./trivy-report.txt ] && [ -s ./trivy-report.txt ]; then
          cat ./trivy-report.txt >> $GITHUB_STEP_SUMMARY
        else
          echo "No vulnerabilities detected or report missing." >> $GITHUB_STEP_SUMMARY
    - name: Push Docker Image
      if: success()
      run: |
        docker buildx imagetools create \
          --tag ghcr.io/adrianw246/last-image:latest \
          ${{ steps.meta.outputs.tags }}
